storage:
  host: 127.0.0.1
  username: root
  password: toor
  database: anonymizer
anonymize:
  core_users:
    iterator:
      name: id
    columns:
      first_name:
        type: first_name
      last_name:
        type: last_name
      middle_name:
        type: middle_name
      email:
        type: email
